-- Supabase SQL Editor에서 실행합니다. 기존 Google Apps Script 데이터는 건드리지 않습니다.
begin;
create schema if not exists wedding_private;
revoke all on schema wedding_private from public, anon, authenticated;
create table if not exists wedding_private.admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table wedding_private.admins enable row level security;
revoke all on wedding_private.admins from public, anon, authenticated;

create or replace function public.wedding_is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from wedding_private.admins where user_id = (select auth.uid()));
$$;
revoke all on function public.wedding_is_admin() from public;
grant execute on function public.wedding_is_admin() to anon, authenticated;

create table if not exists public.wedding_characters (
  id bigint generated by default as identity (start with 100) primary key,
  name text not null check (char_length(btrim(name)) between 1 and 30),
  image_url text,
  storage_path text unique,
  active boolean not null default false,
  season text[] not null default '{}',
  personality text[] not null default '{}',
  features text[] not null default '{}',
  kind text not null default 'human' check (kind in ('human','cat','dog','animal')),
  region integer[],
  atlas_size integer[],
  created_at timestamptz not null default now(),
  check ((image_url is not null)::int + (storage_path is not null)::int = 1),
  check (image_url is null or image_url ~ '^assets/images/[^\r\n]+\.(png|jpg|jpeg|webp)$'),
  check (storage_path is null or storage_path ~ '^guests/[a-z0-9-]+\.(png|jpg|webp)$')
);
create table if not exists public.wedding_gallery (
  id bigint generated by default as identity (start with 100) primary key,
  image_url text,
  storage_path text unique,
  alt text not null default '' check (char_length(alt) <= 120),
  sort_order integer not null default 0,
  visible boolean not null default false,
  created_at timestamptz not null default now(),
  check ((image_url is not null)::int + (storage_path is not null)::int = 1),
  check (image_url is null or image_url ~ '^assets/images/[^\r\n]+\.(png|jpg|jpeg|webp)$'),
  check (storage_path is null or storage_path ~ '^gallery/[a-z0-9-]+\.(png|jpg|webp)$')
);
create table if not exists public.wedding_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 40),
  message text not null check (char_length(btrim(message)) between 1 and 240),
  character_id bigint not null references public.wedding_characters(id) on delete restrict,
  date_label text not null default to_char(now() at time zone 'Asia/Seoul', 'YYYY.MM.DD'),
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  request_id uuid unique,
  legacy_key text unique
);
create index if not exists wedding_message_character_idx on public.wedding_messages(character_id) where visible;
create index if not exists wedding_message_recent_idx on public.wedding_messages(created_at desc, id);
create index if not exists wedding_gallery_sort_idx on public.wedding_gallery(sort_order, id);

alter table public.wedding_characters enable row level security;
alter table public.wedding_gallery enable row level security;
alter table public.wedding_messages enable row level security;
revoke all on public.wedding_characters, public.wedding_gallery, public.wedding_messages from public, anon, authenticated;
grant select on public.wedding_characters, public.wedding_gallery to anon, authenticated;
grant select (id,name,message,character_id,date_label,visible,created_at) on public.wedding_messages to anon, authenticated;
grant insert, update, delete on public.wedding_characters, public.wedding_gallery, public.wedding_messages to authenticated;
grant usage on sequence public.wedding_characters_id_seq, public.wedding_gallery_id_seq to authenticated;

drop policy if exists wedding_messages_read on public.wedding_messages;
create policy wedding_messages_read on public.wedding_messages for select to anon, authenticated
  using (visible or (select public.wedding_is_admin()));
drop policy if exists wedding_characters_read on public.wedding_characters;
create policy wedding_characters_read on public.wedding_characters for select to anon, authenticated
  using (active or (select public.wedding_is_admin()) or exists (
    select 1 from public.wedding_messages m where m.character_id = wedding_characters.id and m.visible
  ));
drop policy if exists wedding_gallery_read on public.wedding_gallery;
create policy wedding_gallery_read on public.wedding_gallery for select to anon, authenticated
  using (visible or (select public.wedding_is_admin()));

drop policy if exists wedding_characters_insert on public.wedding_characters;
create policy wedding_characters_insert on public.wedding_characters for insert to authenticated with check ((select public.wedding_is_admin()));
drop policy if exists wedding_characters_update on public.wedding_characters;
create policy wedding_characters_update on public.wedding_characters for update to authenticated using ((select public.wedding_is_admin())) with check ((select public.wedding_is_admin()));
drop policy if exists wedding_characters_delete on public.wedding_characters;
create policy wedding_characters_delete on public.wedding_characters for delete to authenticated using ((select public.wedding_is_admin()));
drop policy if exists wedding_gallery_insert on public.wedding_gallery;
create policy wedding_gallery_insert on public.wedding_gallery for insert to authenticated with check ((select public.wedding_is_admin()));
drop policy if exists wedding_gallery_update on public.wedding_gallery;
create policy wedding_gallery_update on public.wedding_gallery for update to authenticated using ((select public.wedding_is_admin())) with check ((select public.wedding_is_admin()));
drop policy if exists wedding_gallery_delete on public.wedding_gallery;
create policy wedding_gallery_delete on public.wedding_gallery for delete to authenticated using ((select public.wedding_is_admin()));
drop policy if exists wedding_messages_insert on public.wedding_messages;
create policy wedding_messages_insert on public.wedding_messages for insert to authenticated with check ((select public.wedding_is_admin()));
drop policy if exists wedding_messages_update on public.wedding_messages;
create policy wedding_messages_update on public.wedding_messages for update to authenticated using ((select public.wedding_is_admin())) with check ((select public.wedding_is_admin()));
drop policy if exists wedding_messages_delete on public.wedding_messages;
create policy wedding_messages_delete on public.wedding_messages for delete to authenticated using ((select public.wedding_is_admin()));

-- Anonymous guests can only call this narrow input path. They cannot set visibility,
-- dates, IDs or edit somebody else's message. A retry reuses the same request UUID.
create or replace function public.register_wedding_guest(p_name text, p_message text, p_character_id bigint, p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare result public.wedding_messages;
begin
  if p_name is null or char_length(btrim(p_name)) not between 1 and 12 then
    raise exception '이름은 1~12자로 적어 주세요.';
  end if;
  if p_message is null or char_length(btrim(p_message)) not between 1 and 240 then
    raise exception '축하 메시지는 1~240자로 적어 주세요.';
  end if;
  if p_request_id is null then raise exception '등록 요청 번호가 필요합니다.'; end if;
  select * into result from public.wedding_messages where request_id = p_request_id;
  if found then
    if result.name <> btrim(p_name) or result.message <> btrim(p_message) or result.character_id <> p_character_id then
      raise exception '등록 요청이 일치하지 않습니다. 새로고침 후 다시 시도해 주세요.';
    end if;
    if not result.visible then raise exception '이미 처리된 요청입니다.'; end if;
  else
    perform id from public.wedding_characters where id = p_character_id and active for share;
    if not found then raise exception '이 캐릭터는 지금 선택할 수 없어요. 다른 친구를 골라 주세요.'; end if;
    insert into public.wedding_messages (name,message,character_id,request_id)
      values (btrim(p_name),btrim(p_message),p_character_id,p_request_id)
      on conflict (request_id) do nothing returning * into result;
    if not found then
      select * into result from public.wedding_messages where request_id = p_request_id;
      if result.name <> btrim(p_name) or result.message <> btrim(p_message) or result.character_id <> p_character_id or not result.visible then
        raise exception '등록 요청이 일치하지 않습니다.';
      end if;
    end if;
  end if;
  return jsonb_build_object('id', result.id,'name',result.name,'message',result.message,'character_id',result.character_id,'date_label',result.date_label,'created_at',result.created_at);
end;
$$;
revoke all on function public.register_wedding_guest(text,text,bigint,uuid) from public;
grant execute on function public.register_wedding_guest(text,text,bigint,uuid) to anon, authenticated;

-- Private bucket: hidden new uploads are not served through public bucket URLs.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('wedding-media','wedding-media',false,10485760,array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set public = false, file_size_limit = 10485760, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists wedding_media_read on storage.objects;
create policy wedding_media_read on storage.objects for select to anon, authenticated using (
  bucket_id = 'wedding-media' and (
    (select public.wedding_is_admin())
    or exists (select 1 from public.wedding_gallery g where g.storage_path = name and g.visible)
    or exists (select 1 from public.wedding_characters c where c.storage_path = storage.objects.name and (c.active or exists (
      select 1 from public.wedding_messages m where m.character_id = c.id and m.visible
    )))
  )
);
drop policy if exists wedding_media_insert on storage.objects;
create policy wedding_media_insert on storage.objects for insert to authenticated with check (
  bucket_id = 'wedding-media' and (select public.wedding_is_admin()) and name ~ '^(guests|gallery)/[a-z0-9-]+\.(png|jpg|webp)$'
);
drop policy if exists wedding_media_update on storage.objects;
create policy wedding_media_update on storage.objects for update to authenticated using (
  bucket_id = 'wedding-media' and (select public.wedding_is_admin())
) with check (bucket_id = 'wedding-media' and (select public.wedding_is_admin()));
drop policy if exists wedding_media_delete on storage.objects;
create policy wedding_media_delete on storage.objects for delete to authenticated using (
  bucket_id = 'wedding-media' and (select public.wedding_is_admin())
  and not exists (select 1 from public.wedding_characters c where c.storage_path = storage.objects.name)
  and not exists (select 1 from public.wedding_gallery g where g.storage_path = storage.objects.name)
);
commit;
