-- 초기 이미지 목록입니다. 최초 1회 실행합니다. 삭제 후 다시 실행하면 기본 항목이 복원됩니다.
begin;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (2,'기존 하객 1','assets/images/guests/original-atlas.png',false,array[997,29,229,450],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (3,'기존 하객 2','assets/images/guests/original-atlas.png',false,array[1436,51,241,430],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (4,'기존 하객 3','assets/images/guests/original-atlas.png',false,array[91,489,235,390],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (5,'기존 하객 4','assets/images/guests/original-atlas.png',false,array[549,495,229,384],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (6,'기존 하객 5','assets/images/guests/original-atlas.png',false,array[998,489,225,389],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (7,'기존 하객 6','assets/images/guests/original-atlas.png',false,array[1456,501,218,378],array[1774,887],'{}','{}','{}','human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (8,'봄 소풍러','assets/images/guests/spring-picnic.png',true,null,null,array['봄'],array['다정함'],array['소풍'],'human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (9,'밤하늘 여행자','assets/images/guests/starlight-traveler.png',true,null,null,array['사계절'],array['호기심'],array['별보기'],'human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (10,'장난꾸러기 고양이','assets/images/guests/playful-cat.png',true,null,null,array['사계절'],array['장난꾸러기'],array['고양이'],'cat') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (11,'햇살 강아지','assets/images/guests/sunny-dog.png',true,null,null,array['여름'],array['명랑함'],array['해바라기'],'dog') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (12,'가을 화가','assets/images/guests/autumn-artist.png',true,null,null,array['가을'],array['감성적'],array['그림'],'human') on conflict (id) do nothing;
insert into public.wedding_characters (id,name,image_url,active,region,atlas_size,season,personality,features,kind) values (13,'눈꽃 친구','assets/images/guests/snowflake-friend.png',true,null,null,array['겨울'],array['포근함'],array['눈꽃'],'human') on conflict (id) do nothing;
insert into public.wedding_gallery (id,image_url,alt,sort_order,visible) values (1,'assets/images/gallery/wedding-01.jpg','꽃다발을 든 도훈과 웃고 있는 영현의 웨딩 사진',0,true) on conflict (id) do nothing;
commit;
